import Head from "next/head"
import Footer from "./Footer"
import Navbar from "./Navbar"

type NavbarProps = {
  children: JSX.Element
}

const Layout = ({ children }: NavbarProps) => {
  return (
    <>
      <Head>
        <title>J.Doe</title>
        <meta
          name='description'
          content='Generated by create-t3-app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className='bg-blue'>
        <Navbar />
        <section className='flex flex-col md:flex-row min-h-screen md:min-h-[calc(100vh_-_6rem)]  overflow-x-hidden relative pt-12 justify-center'>
          {children}
        </section>

        <Footer />
      </main>
    </>
  )
}

export default Layout
